name: Test SHFE Crawler

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run SHFE crawler
        run: |
          python crawler/shfe.py
