name: Update Data

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install packages
        run: |
          pip install -r requirements.txt


      - name: Run Python
        run: python crawler/update_all.py


      - name: Commit JSON
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add data/announcements.json

          if ! git diff --cached --quiet; then
            git commit -m "Auto update data"
            git push
          fi
